```{r}
library(packcircles)
library(ggplot2)
library(viridis)
library(ggiraph)
```

```{r}
# Create data
data <- read.csv('data_sun.csv', stringsAsFactors = TRUE)
data <- data.frame(country = data$country, value = data$new_cases)
data <- na.omit(data)
```

```{r}
# Add a column with the text you want to display for each bubble:
data$text <- paste("name: ",data$country, "\n", "value:", data$value, "\n", "You can add a story here!")
```

```{r}
# Generate the layout
packing <- circleProgressiveLayout(data$value, sizetype='area')
data <- cbind(data, packing)
dat.gg <- circleLayoutVertices(packing, npoints=50)
```

```{r}
# Make the plot with a few differences compared to the static version:
p <- ggplot() + 
  geom_polygon_interactive(data = dat.gg, aes(x, y, group = id, fill=id, tooltip = data$text[id], data_id = id), colour = "black", alpha = 0.6) +
  scale_fill_viridis() +
  geom_text(data = data, aes(x, y, label = gsub("Country_", "",country)), size=2, color="black") +
  theme_void() + 
  theme(legend.position="none", plot.margin=unit(c(0,0,0,0),"cm") ) + 
  coord_equal()
```
```{r}
# Turn it interactive
widg <- ggiraph(ggobj = p, width_svg = 7, height_svg = 7)
```
```{r}
library(htmlwidgets)
saveWidget(widg, file=paste0( getwd(), "/circle_packing.html"))
```